### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by docfaizal** [pystardust/ani-cli#1044]
Version: 4.1.0
OS: DF_OS
Shell: fish
Anime: any args

**Describe the bug**
connection error and  No results found on any args
![2023-02-23-165536_1366x768_scrot](https://user-images.githubusercontent.com/107258640/220893739-b8887269-9a4a-4c15-baa5-9d6073c6628e.png)

**Steps To Reproduce**

1. Run `ani-cli (anything except -h and -V)`

**Comment by static7777** [comment]
Was solved for me by updating my client (I get it from the AUR so I don't use -U to update)

Since the -U flag doesn't work for you I would suggest re-installing ani-cli

**Comment by port19x** [comment]
> Was solved for me by updating my client (I get it from the AUR so I don't use -U to update)
> 
> Since the -U flag doesn't work for you I would suggest re-installing ani-cli

Sadly this is an issue on our end.
We broke `-U` in the 4.1.0 release.

#1039

**Comment by port19x** [comment]
It's resolved in 4.1.1 and onwards, but for AUR users there will be no fix unless installing -git or waiting for 4.2.0

We deemed it acceptable to wait with another release, as point release users typically upgrade via their package manager anyway

**Comment by Sparrow1827** [comment]
I am using ver 4.1.3  (the git version from AUR) and the error is still present in my case. I can't search for any anime...
![swappy-20230225_210719](https://user-images.githubusercontent.com/87923259/221365824-6b01a60f-7ced-4208-a9cc-342484508d37.png)

**Comment by Betweenthelines** [comment]
> I am using ver 4.1.3 (the git version from AUR) and the error is still present in my case. I can't search for any anime... OS : Arch Linux Shell : ZSH
> 
> ![swappy-20230225_210719](https://user-images.githubusercontent.com/87923259/221365824-6b01a60f-7ced-4208-a9cc-342484508d37.png)

same thing happening to me

**Comment by docfaizal** [comment]
![2023-02-26-151905_1366x768_scrot](https://user-images.githubusercontent.com/107258640/221403561-a4021a96-2c2d-4c20-bfe4-c27911af1c6b.png)

for me also the error still perist

**Comment by Betweenthelines** [comment]
> ![2023-02-26-151905_1366x768_scrot](https://user-images.githubusercontent.com/107258640/221403561-a4021a96-2c2d-4c20-bfe4-c27911af1c6b.png)
> 
> for me also the error still perist

Can confirm it still persists
![screenshot_2023-02-26-32_1920x1080](https://user-images.githubusercontent.com/109682700/221413920-10345df2-e8d5-4c81-8d7d-04b7cf6c82ef.png)
