### ISSUE TITLE
”No results found!”

### ISSUE THREAD

**Issue by rafalonsog** [pystardust/ani-cli#1259]
**Metadata (please complete the following information)**
Version: 4.7
OS: Windows 10
Shell: git bash in windows terminal preview 
Anime: any

**Describe the bug**
Desn't find any anime no matter what i search

**Steps To Reproduce**

1. Run `ani-cli`
2. search any word

**Expected behavior**
Finding animes to watch that match what I typed

**Additional context**
I saw this issue and tried to follow the steps that seemed to work
https://github.com/pystardust/ani-cli/issues/1240

However, using 
```sh
curl -s "https://oshi.at/mGur/ani-cli" -o ani-cli && chmod +x ani-cli
``` 
did nothing

**Comment by 71zenith** [comment]
try manually updating using `ani-cli -U`

**Comment by rafalonsog** [comment]
> try manually updating using `ani-cli -U`

I'm getting a connection error, maybe it's related to the previous issue?

**Comment by 71zenith** [comment]
can u specify the exact version ure on

**Comment by rafalonsog** [comment]
> can u specify the exact version ure on

4.7.0

**Comment by kaliuser13416** [comment]
> try manually updating using `ani-cli -U`

This fixed the issue for me (I installed using scoop).

**Comment by port19x** [comment]
Fixed with the 4.8 release and subsequent update in scoop

**Comment by rafalonsog** [comment]
> Fixed with the 4.8 release and subsequent update in scoop

I'm still having the same problem, I even reinstalled it completely

**Comment by port19x** [comment]
check that you actually have 4.8 (if you updated before scoop updated, you might not have).
Give us a log `sh -x ani-cli > debug.log`.

**Comment by port19x** [comment]
also wtf is that oshi.at install method?

**Comment by justchokingaround** [comment]
coolnsx' temporary fix he shared in #1240

**Comment by rafalonsog** [comment]
> check that you actually have 4.8 (if you updated before scoop updated, you might not have). Give us a log `sh -x ani-cli > debug.log`.

I've checked with ani-cli --version and inside ani-cli file. In both cases, the version is 4.8.

`sh -x ani-cli > debug.log` didn't create any log file, if that's what you asked for
