### ISSUE TITLE
Previous watched animes aren't accesible

### ISSUE THREAD

**Issue by an-dr32** [pystardust/ani-cli#474]
So this is a doozy. I'm using a previous commit of the program as the latest commit just refuses to open mpv or any other video player. (Somehow it doesn't even detect VLC on my apps, I'm using a 2010 Macbook with High Sierra, I think it has something to do that in Mac it is named as VLC in all caps and it's trying to find it in lower case and maybe it's case sensitive, who knows) I did the pull request from my previous version but forgot to duplicate it before, the newest version just refused to work, so I went to my Linux machine and copied the previous version I have there and paste it on my Mac but now when I'm trying to access previous watched animes with -c it's giving the error "ani-cli: line 232: [: : integer expression expected" then it shows a [1] and an empty space and it prompts me to chose but there's nothing to choose, also I noticed that is not storing the names of the animes I've watched recently as it only shows the first 9 I watched before the pull request fiasco. If anyone knows the solution for either issue so I can keep using the old version or fix the new one it would be really appreciated.

**Comment by RaynardGerraldo** [comment]
> So this is a doozy. I'm using a previous commit of the program as the latest commit just refuses to open mpv or any other video player. (Somehow it doesn't even detect VLC on my apps, I'm using a 2010 Macbook with High Sierra, I think it has something to do that in Mac it is named as VLC in all caps and it's trying to find it in lower case and maybe it's case sensitive, who knows) I did the pull request from my previous version but forgot to duplicate it before, the newest version just refused to work, so I went to my Linux machine and copied the previous version I have there and paste it on my Mac but now when I'm trying to access previous watched animes with -c it's giving the error "ani-cli: line 232: [: : integer expression expected" then it shows a [1] and an empty space and it prompts me to chose but there's nothing to choose, also I noticed that is not storing the names of the animes I've watched recently as it only shows the first 9 I watched before the pull request fiasco. If anyone knows the solution for either issue so I can keep using the old version or fix the new one it would be really appreciated.

Can you specify latest commit that worked for you?

**Comment by an-dr32** [comment]
> 
Sure, I was using the version 1.1.0.  The 1.5.5 isn't working at all for me. It never starts MPV and just shows the menu that appears after you close MPV to change episodes and all that.

**Comment by RaynardGerraldo** [comment]
> > 
> 
> Sure, I was using the version 1.1.0. The 1.5.5 isn't working at all for me. It never starts MPV and just shows the menu that appears after you close MPV to change episodes and all that.

we are on version 1.6 right now, try updating and reconfirm

**Comment by ura43** [comment]
If you are trying to watch a previously completed anime, that was disabled somewhat recently, when we merged `-u` and `-H` into `-c`

**Comment by an-dr32** [comment]
> > > 
> > 
> > 
> > Sure, I was using the version 1.1.0. The 1.5.5 isn't working at all for me. It never starts MPV and just shows the menu that appears after you close MPV to change episodes and all that.
> 
> we are on version 1.6 right now, try updating and reconfirm

MPV is working now but search history is still not working. It shows this: " ./ani-cli: line 124: [: : integer expression expected " when you use the "[h] search history" option on the menu.
(I finished a couple of episodes, all the way to the end, of two different animes I've already watched before to test.)

**Comment by RaynardGerraldo** [comment]
> > > > 
> > > 
> > > 
> > > Sure, I was using the version 1.1.0. The 1.5.5 isn't working at all for me. It never starts MPV and just shows the menu that appears after you close MPV to change episodes and all that.
> > 
> > 
> > we are on version 1.6 right now, try updating and reconfirm
> 
> MPV is working now but search history is still not working. It shows this: " ./ani-cli: line 124: [: : integer expression expected " when you use the "[h] search history" option on the menu. (I finished a couple of episodes, all the way to the end, of two different animes I've already watched before to test.)

can you confirm that you have .cache/ani-hsts in your home directory?

**Comment by an-dr32** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Sure, I was using the version 1.1.0. The 1.5.5 isn't working at all for me. It never starts MPV and just shows the menu that appears after you close MPV to change episodes and all that.
> > > 
> > > 
> > > we are on version 1.6 right now, try updating and reconfirm
> > 
> > 
> > MPV is working now but search history is still not working. It shows this: " ./ani-cli: line 124: [: : integer expression expected " when you use the "[h] search history" option on the menu. (I finished a couple of episodes, all the way to the end, of two different animes I've already watched before to test.)
> 
> can you confirm that you have .cache/ani-hsts in your home directory? and does it contain anything?

No. There is no such file on my home.

**Comment by 71zenith** [comment]
try using `touch ~/.cache/ani-hsts`

**Comment by an-dr32** [comment]
> touch ~/.cache/ani-hsts

There is the file there in cache and it has a list of anime's I've watched but it's not accessing them. It even has the one's I've watched before the 1.6 pull request. No idea what's going on there.

**Comment by iamchokerman** [comment]
when you run ```ani-cli -V``` does it output 1.6.3?

**Comment by RaynardGerraldo** [comment]
> > when you run `ani-cli -V` does it output 1.6.3?
> 
> Wait... no... it's showing 1.5.5. But I erased that version from my drive.

try the new homebrew installation

**Comment by iamchokerman** [comment]
but first do ```sudo rm /usr/local/bin/ani-cli```

**Comment by RaynardGerraldo** [comment]
> I haven't used brew to install ani-cli cause it does too many weird things in High Sierra and it takes forever to install most things that would take seconds or minutes but this is what came out when I tried it just now:
> 
> Warning: No available formula with the name "ani-cli". Did you mean lean-cli? ==> Searching for similarly named formulae... This similarly named formula was found: lean-cli To install it, run: brew install lean-cli ==> Searching for a previously deleted formula (in the last month)... Error: No previously deleted formula found. ==> Searching taps on GitHub... Error: No formulae found in taps.

are you using the instructions from the latest README?

**Comment by iamchokerman** [comment]
you have to run ```brew tap iamchokerman/ani-cli``` before you install, otherwise it won't work

**Comment by an-dr32** [comment]
> /

So, I tried to follow the instruction of the README and no progress. Same error. Now I'm brewing the install but it's installing a lot of things so I'll update once it's done. Probably next year. Why does it need ca-certificates, aria2, cmake, imath, jpeg, openexr, webp, gnutls, glib, harfbuzz, little-cms2, rubberband, zstd, yt-dlp and openssl? That's a lot.

**Comment by RaynardGerraldo** [comment]
> So, I tried to follow the instruction of the README and no progress. Same error. Now I'm brewing the install but it's installing a lot of things so I'll update once it's done. Probably next year. Why does it need ca-certificates, aria2, cmake, imath, jpeg, openexr, webp, gnutls, glib, harfbuzz, little-cms2, rubberband, zstd, yt-dlp and openssl? That's a lot.

yea thats not suppose to happen, in the mean time try the old installation process

`git clone https://github.com/pystardust/ani-cli
cd ani-cli
cp ani-cli /usr/local/bin/ani-cli
sudo chmod +x /usr/local/bin/ani-cli`

and see if -c is fixed

**Comment by iamchokerman** [comment]
@an-dr32 that's probably happening because you haven't updated some of those homebrew packages in a while, they're not all required (ex: imath and jpeg)

**Comment by an-dr32** [comment]
> @an-dr32 that's probably happening because you haven't updated some of those homebrew packages in a while, they're not all required (ex: imath and jpeg)

Yeah, this is my media machine so I only use it to browse the internet and watch media, besides light coding but for that I use VSCode. Though I use brew to install a few programs. Thought tried again cloning the repository but didn't work.
I checked the code and the line thats referencing is:

while read -r anime_id; do
                current_ep_number="$(search_eps "$anime_id")"
                history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
                if [ "$current_ep_number" -ge "$history_ep_number" ]      <<<<<<: This one
                then
                        # breaks down with \n because of the display functions
                        unwatched_anime="$unwatched_anime$anime_id

Maybe some issue with High Sierra.

**Comment by an-dr32** [comment]
I don't know if it might be relevant but I always go with 720p option as the screen on the 2010 Macbook is not full HD.

**Comment by an-dr32** [comment]
> ./ani-cli: line 124: [: : integer expression expected

"./ani-cli: line 124: [: : integer expression expected"  
when searching for history and it doesn't show previously watched animes or episodes.

**Comment by an-dr32** [comment]
./ani-cli -q 720 -c                                                                                  (ani-cli) 11:17:32
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
./ani-cli: line 124: [: : integer expression expected
No unwatched episodes
[1]
[a] search for another anime
[q] exit
Enter choice: 1
Invalid number entered

This is the whole transcript of what happens

**Comment by iamchokerman** [comment]
what happens when you just try to run ani-cli and watch an anime, without any arguments?

**Comment by an-dr32** [comment]
> what happens when you just try to run ani-cli and watch an anime, without any arguments?

It works. The problem is not streaming, is the database. It's kind of cumbersome to remember names and episodes of all the animes every time I restart the program instead of just going back to the one I finished watching before I turned off the computer. But if it must be done like that, it must be done.

**Comment by RaynardGerraldo** [comment]
> > what happens when you just try to run ani-cli and watch an anime, without any arguments?
> 
> It works. The problem is not streaming, is the database. It's kind of cumbersome to remember names and episodes of all the animes every time I restart the program instead of just going back to the one I finished watching before I turned off the computer. But if it must be done like that, it must be done.

can you drag and drop ur ~/.cache/ani-hsts history file here? im trying to reproduce the problem

**Comment by an-dr32** [comment]
[ani-hsts.txt](https://github.com/pystardust/ani-cli/files/7989185/ani-hsts.txt)
Had to change the extension to txt but here it is.

**Comment by iamchokerman** [comment]
are you 100% sure it's in the ~/.cache/ directory?

**Comment by an-dr32** [comment]
100%. I took it out from there.

**Comment by an-dr32** [comment]
Though permissions are -rw-r--r-- so... maybe a permissions issue?

**Comment by ura43** [comment]
Hmm, that may be an issue, tho read permissions are there

**Comment by RaynardGerraldo** [comment]
> Though permissions are -rw-r--r-- so... maybe a permissions issue?

chmod +w ~/.cache/ani-hsts 

try that

**Comment by an-dr32** [comment]
> > Though permissions are -rw-r--r-- so... maybe a permissions issue?
> 
> chmod +w ~/.cache/ani-hsts
> 
> try that

Still nothing. Same "./ani-cli: line 124: [: : integer expression expected" error.

**Comment by iamchokerman** [comment]
version 1.6.4 right?

**Comment by an-dr32** [comment]
λ git clone https://github.com/pystardust/ani-cli.git                                                            (Github) 16:11:11
Cloning into 'ani-cli'...
remote: Enumerating objects: 1281, done.
remote: Counting objects: 100% (1281/1281), done.
remote: Compressing objects: 100% (562/562), done.
remote: Total 1281 (delta 748), reused 1173 (delta 696), pack-reused 0
Receiving objects: 100% (1281/1281), 313.18 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (748/748), done.
λ cd ani-cli/                                                                                                    (Github) 16:11:51
(master) λ cp ani-cli /usr/local/bin/ani-cli                                                                    (ani-cli) 16:11:58
(master) λ sudo chmod +x /usr/local/bin/ani-cli                                                                 (ani-cli) 16:12:13
(master) λ ani-cli -V                                                                                           (ani-cli) 16:12:28
Version: 1.6.4
(master) λ ani-cli -c                                                                                           (ani-cli) 16:12:40
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
/usr/local/bin/ani-cli: line 124: [: : integer expression expected
No unwatched episodes
[1]
[a] search for another anime
[q] exit
Enter choice: q

**Comment by iamchokerman** [comment]
have you tried watching a few seconds of an episode, and then check again if -c works, since it should be added to the logs

**Comment by an-dr32** [comment]
> have you tried watching a few seconds of an episode, and then check again if -c works, since it should be added to the logs

Yeah. Same thing.

**Comment by iamchokerman** [comment]
that's weird. can you try deleting the ani-hsts file from .cache/ and then running ani-cli again, and show me any error messages you might get?

**Comment by an-dr32** [comment]
It doesn't show the error anymore but now says "History is empty" and after I finish watching something it doesn't add it to the history.

**Comment by iamchokerman** [comment]
what does it now say when you run ani-cli -c?

**Comment by an-dr32** [comment]
> what does it now say when you run ani-cli -c?
 History is empty

**Comment by iamchokerman** [comment]
no other errors?

**Comment by an-dr32** [comment]
> no other errors?

None. It just doesn't read the ani-hsts database in the cache but it does write information in it.
